
export const LOGIN_BEGIN ='LOGIN_BEGIN';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAILURE ='LOGIN_FAILURE';



export const REGISTER_BEGIN ='REGISTER_BEGIN';
export const REGISTER_SUCCESS ='REGISTER_SUCCESS';
export const REGISTER_FAILURE ='REGISTER_FAILURE';


export const GETPRODUCT_BEGIN ='GETPRODUCT_BEGIN';
export const GETPRODUCT_SUCCESS ='GETPRODUCT_SUCCESS';
export const GETPRODUCT_FAILURE ='GETPRODUCT_FAILURE';

export const ADDTOCART_BEGIN ='ADDTOCART_BEGIN';
export const ADDTOCART_SUCCESS ='ADDTOCART_SUCCESS';
export const ADDTOCART_FAILURE ='ADDTOCART_FAILURE';

export const GETTOCART_BEGIN ='GETTOCART_BEGIN';
export const GETTOCART_SUCCESS ='GETTOCART_SUCCESS';
export const GETTOCART_FAILURE ='GETTOCART_FAILURE';


export const PLACEORDER_BEGIN ='PLACEORDER_BEGIN';
export const PLACEORDER_SUCCESS ='PLACEORDER_SUCCESS';
export const PLACEORDER_FAILURE ='PLACEORDER_FAILURE';

export const GETORDER_BEGIN ='GETORDER_BEGIN';
export const GETORDER_SUCCESS ='GETORDER_SUCCESS';
export const GETORDER_FAILURE ='GETORDER_FAILURE';